export const ADD_TO_CART = "ADD_TO_CART";
export const FETCH_NAV_ITEMS = "FETCH_NAV_ITEMS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const SET_PRODUCT_DETAILS = "SET_PRODUCT_DETAILS";
export const ADD_TO_QUANTITY = "ADD_TO_QUANTITY";
export const REDUCE_TO_QUANTITY = "REDUCE_TO_QUANTITY";
export const UPDATE_CART = "UPDATE_CART";
export const SWITCH_CURRENCY = "SWITCH_CURRENCY";
