export const ADD_TO_CART = 'ADD_TO_CART' 
export const FETCH_NAV_ITEMS = 'FETCH_NAV_ITEMS'
export const GET_PRODUCT_DETAILS ='GET_PRODUCT_DETAILS'
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS'